global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3333']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']